// Generated by IcedCoffeeScript 1.7.1-b
(function() {
  var all_select, s, _i, _len;

  all_select = document.querySelectorAll("select");

  console.log(all_select);

  for (_i = 0, _len = all_select.length; _i < _len; _i++) {
    s = all_select[_i];
    s.onmousedown = function() {
      return false;
    };
  }

}).call(this);
